# Generated by Django 5.2.15 on 2026-06-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_icon',
            field=models.CharField(choices=[('👤', 'Predefinito (👤)'), ('🐶', 'Cane (🐶)'), ('🐱', 'Gatto (🐱)'), ('🦊', 'Volpe (🦊)'), ('🐯', 'Tigre (🐯)'), ('🐼', 'Panda (🐼)'), ('🐰', 'Coniglio (🐰)'), ('👽', 'Alieno (👽)'), ('🤖', 'Robot (🤖)'), ('👻', 'Fantasma (👻)'), ('🤠', 'Cowboy (🤠)')], default='👤', max_length=10),
        ),
    ]
