# Generated by Django 5.2.15 on 2026-06-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_icon',
            field=models.CharField(choices=[('👤', 'Default (👤)'), ('🐶', 'Dog (🐶)'), ('🐱', 'Cat (🐱)'), ('🦊', 'Fox (🦊)'), ('🐯', 'Tiger (🐯)'), ('🐼', 'Panda (🐼)'), ('🐰', 'Rabbit (🐰)'), ('👽', 'Alien (👽)'), ('🤖', 'Robot (🤖)'), ('👻', 'Ghost (👻)'), ('🤠', 'Cowboy (🤠)')], default='👤', max_length=10),
        ),
    ]
