# Generated by Django 5.2.15 on 2026-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('listener', 'Listener'), ('curator', 'Curator'), ('moderator', 'Moderator')], default='listener', max_length=20),
        ),
    ]
