# Generated by Django 5.2.15 on 2026-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_icon',
            field=models.CharField(choices=[('👤', '👤'), ('🐶', '🐶'), ('🐱', '🐱'), ('🦊', '🦊'), ('🐯', '🐯'), ('🐼', '🐼'), ('🐰', '🐰'), ('👽', '👽'), ('🤖', '🤖'), ('👻', '👻'), ('🤠', '🤠')], default='👤', max_length=10),
        ),
    ]
