# Generated by Django 5.2.15 on 2026-06-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
