# Generated by Django 5.2.15 on 2026-06-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
