# Generated by Django 5.2.15 on 2026-06-26 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_playlist_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='favorite_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_editorial',
            field=models.BooleanField(default=False),
        ),
    ]
